name: conda
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ "macos-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install conda and solve/verify conda environment
        run: |
          ./install-conda.sh
      - name: Run tests
        run: |
          source ./env.sh
          conda list
          python imports.py
          samtools --version
          bcftools --version
          tabix --version
      - uses: actions/upload-artifact@v4
        with:
          name: environment-pinned-${{ matrix.os }}
          path: environment-pinned-${{ matrix.os }}.yml
  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: environment-pinned
          pattern: environment-pinned-*
